export interface Card {
  id: string;
  playerName: string;
  setName: string;
  teamName?: string;
  parallel: string;
  condition: string;
  priceCents: number;
  frontImageUrl: string;
}

export const MOCK_CARDS: Card[] = [
  {
    id: '1',
    playerName: 'LeBron James',
    setName: 'Prizm',
    teamName: 'Lakers',
    parallel: 'Base',
    condition: 'NM',
    priceCents: 450,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=LeBron+Base',
  },
  {
    id: '2',
    playerName: 'Stephen Curry',
    setName: 'Donruss',
    teamName: 'Warriors',
    parallel: 'Silver',
    condition: 'NM',
    priceCents: 320,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Curry+Silver',
  },
  {
    id: '3',
    playerName: 'Patrick Mahomes',
    setName: 'Select',
    teamName: 'Chiefs',
    parallel: 'Red',
    condition: 'MT',
    priceCents: 680,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Mahomes+Red',
  },
  {
    id: '4',
    playerName: 'Mike Trout',
    setName: 'Topps Chrome',
    teamName: 'Angels',
    parallel: 'Refractor',
    condition: 'NM',
    priceCents: 550,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Trout+Refractor',
  },
  {
    id: '5',
    playerName: 'Giannis Antetokounmpo',
    setName: 'Prizm',
    teamName: 'Bucks',
    parallel: 'Green',
    condition: 'NM',
    priceCents: 420,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Giannis+Green',
  },
  {
    id: '6',
    playerName: 'Justin Herbert',
    setName: 'Prizm',
    teamName: 'Chargers',
    parallel: 'Base',
    condition: 'NM',
    priceCents: 280,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Herbert+Base',
  },
  {
    id: '7',
    playerName: 'Aaron Judge',
    setName: 'Bowman',
    teamName: 'Yankees',
    parallel: 'Chrome',
    condition: 'MT',
    priceCents: 380,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Judge+Chrome',
  },
  {
    id: '8',
    playerName: 'Luka Doncic',
    setName: 'Select',
    teamName: 'Mavericks',
    parallel: 'Prizm',
    condition: 'NM',
    priceCents: 720,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Luka+Prizm',
  },
  {
    id: '9',
    playerName: 'Ja Morant',
    setName: 'Donruss',
    teamName: 'Grizzlies',
    parallel: 'Purple',
    condition: 'NM',
    priceCents: 340,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Morant+Purple',
  },
  {
    id: '10',
    playerName: 'CJ Stroud',
    setName: 'Prizm',
    teamName: 'Texans',
    parallel: 'Silver',
    condition: 'MT',
    priceCents: 490,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Stroud+Silver',
  },
  {
    id: '11',
    playerName: 'Shohei Ohtani',
    setName: 'Topps',
    teamName: 'Dodgers',
    parallel: 'Gold',
    condition: 'NM',
    priceCents: 890,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Ohtani+Gold',
  },
  {
    id: '12',
    playerName: 'Anthony Edwards',
    setName: 'Prizm',
    teamName: 'Timberwolves',
    parallel: 'Base',
    condition: 'NM',
    priceCents: 310,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Edwards+Base',
  },
  {
    id: '13',
    playerName: 'Brock Purdy',
    setName: 'Select',
    teamName: '49ers',
    parallel: 'Blue',
    condition: 'NM',
    priceCents: 220,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Purdy+Blue',
  },
  {
    id: '14',
    playerName: 'Ronald Acuna Jr',
    setName: 'Bowman Chrome',
    teamName: 'Braves',
    parallel: 'Refractor',
    condition: 'MT',
    priceCents: 620,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Acuna+Refractor',
  },
  {
    id: '15',
    playerName: 'Jayson Tatum',
    setName: 'Donruss',
    teamName: 'Celtics',
    parallel: 'Base',
    condition: 'NM',
    priceCents: 290,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Tatum+Base',
  },
  {
    id: '16',
    playerName: 'Tyreek Hill',
    setName: 'Prizm',
    teamName: 'Dolphins',
    parallel: 'Orange',
    condition: 'NM',
    priceCents: 350,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Hill+Orange',
  },
  {
    id: '17',
    playerName: 'Mookie Betts',
    setName: 'Topps Chrome',
    teamName: 'Dodgers',
    parallel: 'Base',
    condition: 'NM',
    priceCents: 270,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Betts+Base',
  },
  {
    id: '18',
    playerName: 'Victor Wembanyama',
    setName: 'Prizm',
    teamName: 'Spurs',
    parallel: 'Silver',
    condition: 'MT',
    priceCents: 1250,
    frontImageUrl: 'https://via.placeholder.com/200x280?text=Wemby+Silver',
  },
];
